language: csharp
solution: Tweak.sln
install:
  - nuget restore Tweak.sln
script:
  - msbuild /p:Configuration=Release Tweak.sln
before_deploy:
  - zip binary.zip bin
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: binary.zip
  on:
    tags: true
