language: csharp
solution: Tweak.sln
install:
  - nuget restore Tweak.sln
script:
  - msbuild /p:Configuration=Release Tweak.sln
before_deploy:
  - zip binary.zip bin
deploy:
  cleanup: false
  provider: releases
  file:
    - binary.zip
  on:
    tags: true
