language: csharp
solution: Tweak.sln
install:
  - nuget restore Tweak.sln
script:
  - msbuild /p:Configuration=Release Tweak.sln
before_deploy:
  - (cd bin && for file in */ ; do zip -r "${file%/}.zip" $file; done)
deploy:
  skip_cleanup: true
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: bin/*.zip
  on:
    tags: true
