language: csharp
solution: Tweak.sln
install:
  - nuget restore Tweak.sln
script:
  - msbuild /p:Configuration=Release Tweak.sln
before_deploy:
  - zip -r bin/Release.zip bin/Release
deploy:
  skip_cleanup: true
  provider: releases
  token: $GITHUB_TOKEN
  file: bin/Release.zip
  on:
    tags: true
