language: csharp
solution: Tweak.sln
install:
  - nuget restore Tweak.sln
script:
  - msbuild /p:Configuration=Release Tweak.sln
before_deploy:
  - zip binary.zip bin
deploy:
  skip_cleanup: true
  provider: releases
  files:
    - binary.zip
  on:
    tags: true
